name: dispim_visualization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - notebook
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipywidgets
  - dask
  - dask-image
  - scikit-image
  - napari
  - flask
  - pip
  - pip:
    - tifffile
    - aicsimageio
    - ome-types
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - SimpleITK

